/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csia;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author VivoBook
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        time();
        
       
    }
    public void time(){
    Thread t;
        t = new Thread(){    
            public void run(){
                while(true){
                    DateFormat dateFormat1 = new SimpleDateFormat("dd:MM:yyyy");
                    DateFormat dateFormat2 = new SimpleDateFormat("HH:mm:ss");
                    Date date1 = new Date();
                    Date date2 = new Date();
                    String formateddate1= dateFormat1.format(date1);
                    String formateddate2= dateFormat2.format(date2);
                    
                    jLabel5.setText("Date: " + formateddate1);
                    jLabel6.setText("Time: " + formateddate2);
                    try{sleep(1000);
                    }catch(InterruptedException e){
                        JOptionPane.showMessageDialog(null, "There has been an error:" + e); 
                    }
                }
            }
        };
    t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        DashboardLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UpdateDatabasejFrame = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ViewPatientDatabasejFrame = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        InvoiceCreatorjFrame = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AppointmentCreatorjFrame = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel2.setBackground(new java.awt.Color(255, 202, 212));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(157, 129, 139));

        DashboardLabel.setBackground(new java.awt.Color(157, 129, 139));
        DashboardLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 60)); // NOI18N
        DashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        DashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DashboardLabel.setText("Dashboard");

        jPanel1.setBackground(new java.awt.Color(244, 172, 183));

        UpdateDatabasejFrame.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        UpdateDatabasejFrame.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDatabasejFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpdateDatabasejFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_database_administrator_26px.png"))); // NOI18N
        UpdateDatabasejFrame.setText("Update patient database");
        UpdateDatabasejFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateDatabasejFrameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateDatabasejFrameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateDatabasejFrameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateDatabasejFrameMousePressed(evt);
            }
        });
        UpdateDatabasejFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdateDatabasejFrameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(UpdateDatabasejFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateDatabasejFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(244, 172, 183));

        ViewPatientDatabasejFrame.setBackground(new java.awt.Color(244, 172, 183));
        ViewPatientDatabasejFrame.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        ViewPatientDatabasejFrame.setForeground(new java.awt.Color(255, 255, 255));
        ViewPatientDatabasejFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewPatientDatabasejFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_database_26px.png"))); // NOI18N
        ViewPatientDatabasejFrame.setText("View patient database");
        ViewPatientDatabasejFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPatientDatabasejFrameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewPatientDatabasejFrameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewPatientDatabasejFrameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ViewPatientDatabasejFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewPatientDatabasejFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(244, 172, 183));

        InvoiceCreatorjFrame.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        InvoiceCreatorjFrame.setForeground(new java.awt.Color(255, 255, 255));
        InvoiceCreatorjFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InvoiceCreatorjFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_bill_26px.png"))); // NOI18N
        InvoiceCreatorjFrame.setText("Invoice creator");
        InvoiceCreatorjFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoiceCreatorjFrameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InvoiceCreatorjFrameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvoiceCreatorjFrameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvoiceCreatorjFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvoiceCreatorjFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(244, 172, 183));

        AppointmentCreatorjFrame.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        AppointmentCreatorjFrame.setForeground(new java.awt.Color(255, 255, 255));
        AppointmentCreatorjFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppointmentCreatorjFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_planner_26px.png"))); // NOI18N
        AppointmentCreatorjFrame.setText("Appointment creator");
        AppointmentCreatorjFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentCreatorjFrameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AppointmentCreatorjFrameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AppointmentCreatorjFrameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppointmentCreatorjFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppointmentCreatorjFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(157, 129, 139));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(DashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DashboardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p){
    
     p.setBackground(new Color(255,218,220));
 
     }    
    public void removeColor(JPanel p){
   
     p.setBackground(new Color(244,172,183));   
     } 
    private void UpdateDatabasejFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDatabasejFrameMouseEntered
     setColor(jPanel1);
    }//GEN-LAST:event_UpdateDatabasejFrameMouseEntered

    private void UpdateDatabasejFrameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDatabasejFrameMouseExited
     removeColor(jPanel1);
    }//GEN-LAST:event_UpdateDatabasejFrameMouseExited

    private void ViewPatientDatabasejFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPatientDatabasejFrameMouseEntered
     setColor(jPanel2);
    }//GEN-LAST:event_ViewPatientDatabasejFrameMouseEntered

    private void ViewPatientDatabasejFrameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPatientDatabasejFrameMouseExited
    removeColor(jPanel2);
    }//GEN-LAST:event_ViewPatientDatabasejFrameMouseExited

    private void InvoiceCreatorjFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceCreatorjFrameMouseEntered
    setColor(jPanel3);
    }//GEN-LAST:event_InvoiceCreatorjFrameMouseEntered

    private void InvoiceCreatorjFrameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceCreatorjFrameMouseExited
    removeColor(jPanel3);
    }//GEN-LAST:event_InvoiceCreatorjFrameMouseExited

    private void AppointmentCreatorjFrameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentCreatorjFrameMouseEntered
    setColor(jPanel4);
    }//GEN-LAST:event_AppointmentCreatorjFrameMouseEntered

    private void AppointmentCreatorjFrameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentCreatorjFrameMouseExited
    removeColor(jPanel4);
    }//GEN-LAST:event_AppointmentCreatorjFrameMouseExited

    private void UpdateDatabasejFrameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateDatabasejFrameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateDatabasejFrameKeyPressed

    private void UpdateDatabasejFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDatabasejFrameMouseClicked
            
    }//GEN-LAST:event_UpdateDatabasejFrameMouseClicked

    private void ViewPatientDatabasejFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPatientDatabasejFrameMouseClicked
            Access_Patient_Database edit= new Access_Patient_Database ();
            edit.setVisible(true);
            this.setVisible(false);
            this.dispose();
    }//GEN-LAST:event_ViewPatientDatabasejFrameMouseClicked

    private void InvoiceCreatorjFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceCreatorjFrameMouseClicked
            Invoice_Manager a= new Invoice_Manager();
            a.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_InvoiceCreatorjFrameMouseClicked

    private void UpdateDatabasejFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDatabasejFrameMousePressed
            Modify_Patient_Database a= new Modify_Patient_Database();
            a.setVisible(true);
            this.setVisible(false);
            this.dispose();
    }//GEN-LAST:event_UpdateDatabasejFrameMousePressed

    private void AppointmentCreatorjFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentCreatorjFrameMouseClicked
            Appointment_Database a= new Appointment_Database();
            a.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_AppointmentCreatorjFrameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppointmentCreatorjFrame;
    private javax.swing.JLabel DashboardLabel;
    private javax.swing.JLabel InvoiceCreatorjFrame;
    private javax.swing.JPanel Panel2;
    private javax.swing.JLabel UpdateDatabasejFrame;
    private javax.swing.JLabel ViewPatientDatabasejFrame;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
