/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csia;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.ArrayList;
import java.util.Iterator;



/**
 *
 * @author VivoBook
 */
public class Invoice_Manager extends javax.swing.JFrame {
    public Connection conn=null;
    public ResultSet rs = null;
    public PreparedStatement pst=null;
    
    
   
    
//    public void ShowTableData(){
//    try{
//    conn = ReusableClasses.dbconnection.connection();
//    String populatedatabase = "SELECT * FROM clinic_database.patients;";
//    pst = conn.prepareStatement(populatedatabase);
//    rs = pst.executeQuery();
//    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//    jTable1.getColumnModel().getColumn(3).setMinWidth(0);
//    jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
//    jTable1.getColumnModel().getColumn(5).setMinWidth(0);
//    jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
//    jTable1.getColumnModel().getColumn(6).setMinWidth(0);
//    jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
//    jTable1.getColumnModel().getColumn(7).setMinWidth(0);
//    jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
//    jTable1.getColumnModel().getColumn(8).setMinWidth(0);
//    jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
//    } catch(SQLException e){  
//    }
//    }
    public void ShowTableData(){
    try{
    conn = ReusableClasses.dbconnection.connection();
    String populatedatabase = "SELECT * FROM clinic_database.invoicetable;";
    pst = conn.prepareStatement(populatedatabase);
    rs = pst.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    
    

    } catch(SQLException e){  
    }
    }
    
    Invoice_Viewer SelectedData = new Invoice_Viewer();
    
  
    
   
    
    public Invoice_Manager(){
        initComponents();
//        ShowTableData();
        ShowTableData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanelReceipt = new javax.swing.JPanel();
        OptionsPanel = new javax.swing.JPanel();
        InvoicePanelColorChange1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        InvoicePanelColorChange2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        InvoicePanelColorChange3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ExaminationCheckbox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        HeliofillCheckbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        receiptage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Dentalcheckbox = new javax.swing.JCheckBox();
        receiptlastname = new javax.swing.JTextField();
        TartarCheckbox = new javax.swing.JCheckBox();
        receiptname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        receiptID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        NumberCheck = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        receiptadditionalprocedure = new javax.swing.JTextField();
        receiptadditionalprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanelReceipt.setBackground(new java.awt.Color(255, 202, 212));
        MainPanelReceipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OptionsPanel.setBackground(new java.awt.Color(229, 152, 155));

        InvoicePanelColorChange1.setBackground(new java.awt.Color(181, 131, 141));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Create an invoice");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout InvoicePanelColorChange1Layout = new javax.swing.GroupLayout(InvoicePanelColorChange1);
        InvoicePanelColorChange1.setLayout(InvoicePanelColorChange1Layout);
        InvoicePanelColorChange1Layout.setHorizontalGroup(
            InvoicePanelColorChange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelColorChange1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        InvoicePanelColorChange1Layout.setVerticalGroup(
            InvoicePanelColorChange1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelColorChange1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        InvoicePanelColorChange2.setBackground(new java.awt.Color(181, 131, 141));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("View invoices");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout InvoicePanelColorChange2Layout = new javax.swing.GroupLayout(InvoicePanelColorChange2);
        InvoicePanelColorChange2.setLayout(InvoicePanelColorChange2Layout);
        InvoicePanelColorChange2Layout.setHorizontalGroup(
            InvoicePanelColorChange2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelColorChange2Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        InvoicePanelColorChange2Layout.setVerticalGroup(
            InvoicePanelColorChange2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelColorChange2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_settings_26px.png"))); // NOI18N
        jLabel12.setText("Options");

        InvoicePanelColorChange3.setBackground(new java.awt.Color(181, 131, 141));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Exit");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout InvoicePanelColorChange3Layout = new javax.swing.GroupLayout(InvoicePanelColorChange3);
        InvoicePanelColorChange3.setLayout(InvoicePanelColorChange3Layout);
        InvoicePanelColorChange3Layout.setHorizontalGroup(
            InvoicePanelColorChange3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelColorChange3Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        InvoicePanelColorChange3Layout.setVerticalGroup(
            InvoicePanelColorChange3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePanelColorChange3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout OptionsPanelLayout = new javax.swing.GroupLayout(OptionsPanel);
        OptionsPanel.setLayout(OptionsPanelLayout);
        OptionsPanelLayout.setHorizontalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InvoicePanelColorChange1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InvoicePanelColorChange2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InvoicePanelColorChange3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OptionsPanelLayout.setVerticalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(InvoicePanelColorChange1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(InvoicePanelColorChange2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(InvoicePanelColorChange3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        MainPanelReceipt.add(OptionsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 650));

        jPanel5.setBackground(new java.awt.Color(255, 202, 212));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 52)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Invoice manager");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        MainPanelReceipt.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, -1, 1130, 150));

        jPanel3.setBackground(new java.awt.Color(255, 202, 212));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 21, 96, 22));

        ExaminationCheckbox.setBackground(new java.awt.Color(255, 202, 212));
        ExaminationCheckbox.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        ExaminationCheckbox.setForeground(new java.awt.Color(102, 102, 102));
        ExaminationCheckbox.setText("Examination");
        ExaminationCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminationCheckboxActionPerformed(evt);
            }
        });
        jPanel3.add(ExaminationCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 201, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Last name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 112, 96, -1));

        HeliofillCheckbox.setBackground(new java.awt.Color(255, 202, 212));
        HeliofillCheckbox.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        HeliofillCheckbox.setForeground(new java.awt.Color(102, 102, 102));
        HeliofillCheckbox.setText("Helio fill");
        HeliofillCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeliofillCheckboxActionPerformed(evt);
            }
        });
        jPanel3.add(HeliofillCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 201, 125, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("First name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 66, 96, 25));

        receiptage.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel3.add(receiptage, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 159, 176, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Age");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 160, 96, -1));

        Dentalcheckbox.setBackground(new java.awt.Color(255, 202, 212));
        Dentalcheckbox.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        Dentalcheckbox.setForeground(new java.awt.Color(102, 102, 102));
        Dentalcheckbox.setText("Dental treatment");
        Dentalcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DentalcheckboxActionPerformed(evt);
            }
        });
        jPanel3.add(Dentalcheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 264, -1, -1));

        receiptlastname.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        receiptlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptlastnameActionPerformed(evt);
            }
        });
        jPanel3.add(receiptlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 111, 176, -1));

        TartarCheckbox.setBackground(new java.awt.Color(255, 202, 212));
        TartarCheckbox.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        TartarCheckbox.setForeground(new java.awt.Color(102, 102, 102));
        TartarCheckbox.setText("Tartar removal");
        TartarCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TartarCheckboxActionPerformed(evt);
            }
        });
        jPanel3.add(TartarCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 264, -1, -1));

        receiptname.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel3.add(receiptname, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 66, 176, -1));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 0, 523, 414));

        receiptID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptIDActionPerformed(evt);
            }
        });
        receiptID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                receiptIDKeyReleased(evt);
            }
        });
        jPanel3.add(receiptID, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 21, 176, 27));

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Generate invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 455, -1, 41));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pricing");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 347, 63, -1));

        NumberCheck.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        NumberCheck.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(NumberCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 421, 405, 26));

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Print invoice");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 454, 175, 41));

        receiptadditionalprocedure.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel3.add(receiptadditionalprocedure, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 313, 115, -1));

        receiptadditionalprice.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        receiptadditionalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptadditionalpriceActionPerformed(evt);
            }
        });
        receiptadditionalprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                receiptadditionalpriceKeyTyped(evt);
            }
        });
        jPanel3.add(receiptadditionalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 313, 123, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Procedure");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 347, -1, -1));

        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Search by ID");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 21, -1, -1));

        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 102, 102));
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 454, 175, 41));

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 202, 212));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Print Table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Search by User ID");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setText("Show all");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(45, 45, 45)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton4, jButton5, jButton6});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ID))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton4, jButton5, jButton6});

        jTabbedPane1.addTab("tab2", jPanel4);

        MainPanelReceipt.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanelReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanelReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void setColor(JPanel p){
    
     p.setBackground(new Color(185,148,155));
 
     }    
    public void removeColor(JPanel p){
   
     p.setBackground(new Color(181,131,141));   
     } 
    private void receiptlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptlastnameActionPerformed

    private void HeliofillCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeliofillCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeliofillCheckboxActionPerformed

    private void DentalcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DentalcheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DentalcheckboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(receiptname.getText().isEmpty() || receiptID.getText().isEmpty() || receiptlastname.getText().isEmpty() || receiptage.getText().isEmpty()){
       JOptionPane.showMessageDialog(null,"There are empty fields, please try again!"); 
       
      
       }else{
        
        
       int f=0;
       int i = new Random().nextInt(1000000) + 100000; 
       Date obj= new Date();      
       SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd"); 
       String date= obj.toString();
       String strDate= formatter.format(obj); 
       
       area.setText(area.getText()+ date);
       int finalPrice=0;     
       if(ExaminationCheckbox.isSelected()){
       finalPrice= finalPrice+ 10;   
       }
       if(HeliofillCheckbox.isSelected()){
       finalPrice= finalPrice+ 25;    
       }
       if(TartarCheckbox.isSelected()){
       finalPrice= finalPrice+ 35;    
       }
       if(Dentalcheckbox.isSelected()){
       finalPrice= finalPrice+ 20;     
       }       
       String temp1 = receiptadditionalprice.getText();       
       
       if(temp1.isEmpty()){
       }
       else{
       int additionalprice = Integer.parseInt(temp1);
       finalPrice = finalPrice+additionalprice;      
       }      
       area.setText( "\n================================================================================\n" );
       area.setText(area.getText()+"Date:\t\t\t "+ date + "\n\n" );
       area.setText(area.getText()+"Invoice ID:\t\t\t "+ i + "\n\n" );
       area.setText(area.getText()+"Patient ID:\t\t\t "+ receiptID.getText() + "\n\n"  );
       area.setText(area.getText()+"First name:\t\t\t "+ receiptname.getText() + "\n\n" );
       area.setText(area.getText()+"Last name :\t\t\t "+ receiptlastname.getText() + "\n\n"); 
       area.setText(area.getText()+"Age:\t\t\t "+ receiptage.getText() + "\n\n" );
       if(receiptadditionalprocedure.getText().isEmpty()){
       area.setText(area.getText()+"Additional procedure:\t\t "+ "No additional procedures" + "\n\n");      
       }
       else{
       area.setText(area.getText()+"Additional procedure:\t\t "+ receiptadditionalprocedure.getText() + "\n\n");
       }
       area.setText(area.getText()+"Final price:\t\t\t "+ finalPrice + "€" + "\n\n");     
       area.setText(area.getText()+"Procedures done:");
       if(ExaminationCheckbox.isSelected()){
       area.setText(area.getText() +"\t\t"+ "Examination" + "\n\n");
       }
       if(HeliofillCheckbox.isSelected()){
       area.setText(area.getText()+"\t\t\t"+ "Heliofill" + "\n\n");
       }
       if(TartarCheckbox.isSelected()){
       area.setText(area.getText()+"\t\t\t"+ "Tartar removal" + "\n\n");
       }
       if(Dentalcheckbox.isSelected()){  
       area.setText(area.getText()+"\t\t\t"+ "Dental treatment" + "\n\n");
       }     
       area.setText(area.getText()+"\t\t\t"+ receiptadditionalprocedure.getText() + "\n\n");
       SimpleDateFormat receiptdateobject = new SimpleDateFormat("dd/MM/yyyy");
       
       int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog (null, "Are you sure?","WARNING", dialogButton);
            if(dialogButton == JOptionPane.YES_OPTION) {
                f=1;
               if(dialogButton == JOptionPane.NO_OPTION) {
               f=0;                 
                }
              }

       if(f==1){
       try{
       conn = ReusableClasses.dbconnection.connection(); 
       String insertquerry= "INSERT INTO `clinic_database`.`invoicetable` (`InvoiceID`, `First Name`, `Last Name`, `PatientID`, `Price`, `Date`, `Procedure` ) VALUES (?, ?, ?, ?, ?, ?, ?);" ; 
       String receiptdate = receiptdateobject.format(obj);
       pst = conn.prepareStatement(insertquerry);
       int invoiceid = new Random().nextInt(90000) + 100000;
       
       String str = String.valueOf(invoiceid);
       pst.setString(1, str);
       pst.setString(2, receiptname.getText());
       pst.setString(3, receiptlastname.getText());
       pst.setString(4, receiptID.getText());
       String finalprice = Integer.toString(finalPrice) + "€";
       pst.setString(5, finalprice);
       pst.setString(6, strDate);
       ArrayList<String> procedure = new ArrayList<>();
       if(ExaminationCheckbox.isSelected()){
       String examination = "Examination";
       
       procedure.add(examination);
       }

       if(HeliofillCheckbox.isSelected()){
       String helio = "Heliofill";
       procedure.add(helio);
       }
       if(TartarCheckbox.isSelected()){
       String tartar = "Tartar";
       procedure.add(tartar);
       }
       if(Dentalcheckbox.isSelected()){  
       String dental = "Dental Treatment";
       procedure.add(dental);
       }
       String additional = receiptadditionalprocedure.getText();
       if(additional.isEmpty()){
       }else{
       
       procedure.add(additional);
       }
       StringBuilder sb = new StringBuilder();
           for (String s : procedure) {
               sb.append(s);
               sb.append(", ");
           }
       pst.setString(7, sb.toString());
       pst.executeUpdate();    
       }catch(SQLException e){  
           System.out.println(e);
       }}
       
       ShowTableData();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExaminationCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminationCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExaminationCheckboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{       
        area.print();       
        }catch(PrinterException e){        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void receiptadditionalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptadditionalpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptadditionalpriceActionPerformed

    private void TartarCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TartarCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TartarCheckboxActionPerformed

    private void receiptadditionalpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiptadditionalpriceKeyTyped
     try{
     int check = Integer.parseInt(receiptadditionalprice.getText());
     NumberCheck.setText("");    
     } catch(NumberFormatException e){    
     NumberCheck.setText("Please enter a number");   
     }
    if(receiptadditionalprice.getText().isEmpty()){
    
    NumberCheck.setText("");   
    }  
    }//GEN-LAST:event_receiptadditionalpriceKeyTyped

    private void receiptIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiptIDKeyReleased
     
    }//GEN-LAST:event_receiptIDKeyReleased

    private void receiptIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptIDActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
     jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
    jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
            setColor(InvoicePanelColorChange1);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
            removeColor(InvoicePanelColorChange1);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
            setColor(InvoicePanelColorChange2);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
            removeColor(InvoicePanelColorChange2);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     String SearchID = receiptID.getText();
     String searchquerry="Select * FROM `clinic_database`.`patients` WHERE (`ID` = '" + SearchID +"');" ;
     try{
     pst = conn.prepareStatement(searchquerry);
     rs = pst.executeQuery();
     
     if(rs.next()){
     
     String firsname = rs.getString("First name");
     String lastname = rs.getString("Last name");
     String age = rs.getString("Age");
     receiptname.setText(firsname);
     receiptlastname.setText(lastname);
     receiptage.setText(age);  
     }else{
     JOptionPane.showMessageDialog(null, "ID has not been found, please try again!");
        
     }
     
     
    
    }catch(Exception E){
    
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        try{jTable1.print();}catch(Exception s){
        System.out.println(s);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        Dashboard Dash= new Dashboard ();
        Dash.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
       setColor(InvoicePanelColorChange3);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
       removeColor(InvoicePanelColorChange3);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
        int selectedRowIndex = jTable1.getSelectedRow();
        DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
        
        
        String InvoiceID = model1.getValueAt(selectedRowIndex, 0).toString();
        
        
        String FirstName = model1.getValueAt(selectedRowIndex, 1).toString();
        
        String LastName = model1.getValueAt(selectedRowIndex, 2).toString();
        
        String PatientID= model1.getValueAt(selectedRowIndex, 3).toString(); 

        String Price = model1.getValueAt(selectedRowIndex, 4).toString();

        String Date = model1.getValueAt(selectedRowIndex, 5).toString();

        String Procedure = model1.getValueAt(selectedRowIndex, 6).toString();
        
        Invoice_Viewer ReceiptData = new Invoice_Viewer();
        ReceiptData.setVisible(true);
        ReceiptData.pack();
        ReceiptData.setLocationRelativeTo(null);
        ReceiptData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);   
        
        
        Invoice_Viewer.ReceiptArea.setText( "\n===================================================================================\n" );
        Invoice_Viewer.ReceiptArea.setText(Invoice_Viewer.ReceiptArea.getText()+"Date:\t\t\t\t"+ Date + "\n\n" );
        Invoice_Viewer.ReceiptArea.setText(Invoice_Viewer.ReceiptArea.getText()+"Invoice ID:\t\t\t\t"+ InvoiceID + "\n\n" );
        Invoice_Viewer.ReceiptArea.setText(Invoice_Viewer.ReceiptArea.getText()+"Patient ID:\t\t\t\t"+ PatientID + "\n\n"  );
        Invoice_Viewer.ReceiptArea.setText(Invoice_Viewer.ReceiptArea.getText()+"First name:\t\t\t\t"+ FirstName + "\n\n" );
        Invoice_Viewer.ReceiptArea.setText(Invoice_Viewer.ReceiptArea.getText()+"Last name:\t\t\t\t"+ LastName + "\n\n"); 
        Invoice_Viewer.ReceiptArea.setText(Invoice_Viewer.ReceiptArea.getText()+"Procedures done:\t\t\t"+ Procedure +"\n\n");
        Invoice_Viewer.ReceiptArea.setText(Invoice_Viewer.ReceiptArea.getText()+"Price:\t\t\t\t"+ Price + "\n\n" );
        
        }catch(Exception e){
        
        
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      String searchquerry="Select * FROM `clinic_database`.`invoicetable`";
      try{
      pst = conn.prepareStatement(searchquerry);
      rs = pst.executeQuery();
      jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(SQLException E){
    
     }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      String SearchID = ID.getText();
      String searchquerry="Select * FROM `clinic_database`.`invoicetable` WHERE (`PatientID` = '" + SearchID +"');" ;
      try{
      pst = conn.prepareStatement(searchquerry);
      rs = pst.executeQuery();
      jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(SQLException E){
    
     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       area.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice_Manager().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Dentalcheckbox;
    private javax.swing.JCheckBox ExaminationCheckbox;
    private javax.swing.JCheckBox HeliofillCheckbox;
    private javax.swing.JTextField ID;
    private javax.swing.JPanel InvoicePanelColorChange1;
    private javax.swing.JPanel InvoicePanelColorChange2;
    private javax.swing.JPanel InvoicePanelColorChange3;
    private javax.swing.JPanel MainPanelReceipt;
    private javax.swing.JLabel NumberCheck;
    private javax.swing.JPanel OptionsPanel;
    private javax.swing.JCheckBox TartarCheckbox;
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField receiptID;
    private javax.swing.JTextField receiptadditionalprice;
    private javax.swing.JTextField receiptadditionalprocedure;
    private javax.swing.JTextField receiptage;
    private javax.swing.JTextField receiptlastname;
    private javax.swing.JTextField receiptname;
    // End of variables declaration//GEN-END:variables
}
